/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class MainTest {
  public static void main(String[] args) {
    try {
      LlmClient client = new LlmClient();
      System.out.println(client.GenerateText("Hello world"));
    } catch (Exception e) {
      // TODO: handle exception
      e.printStackTrace();
    }
  }
}
